# Generated by Django 5.0.6 on 2025-11-28 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_home', 'Google Home'), ('nest', 'Nest'), ('ring', 'Ring'), ('other', 'Other')], max_length=32)),
                ('display_name', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('background_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('camera', 'Camera'), ('thermostat', 'Thermostat'), ('sensor', 'Sensor')], max_length=32)),
                ('integration', models.CharField(choices=[('local', 'Local'), ('google_home', 'Google Home'), ('nest', 'Nest'), ('ring', 'Ring'), ('other', 'Other')], default='local', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('is_on', models.BooleanField(default=False)),
                ('position_x', models.FloatField(default=10.0, help_text='Percentage from left (0-100)')),
                ('position_y', models.FloatField(default=10.0, help_text='Percentage from top (0-100)')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='automation.room')),
            ],
        ),
    ]
