# Generated by Django 5.0.6 on 2025-11-28 22:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['room', 'name']},
        ),
        migrations.AlterModelOptions(
            name='integration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable a device without deleting it.'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text="Optional location label, e.g. 'Near window', 'Ceiling', etc.", max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable an integration without deleting it.'),
        ),
        migrations.AddField(
            model_name='integration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When we last synced with this integration, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Uploaded background image for this room.', null=True, upload_to='room_backgrounds/'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, help_text="Optional short description, e.g. 'Main family room'.", max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable a room without deleting it.'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary device-specific configuration payload.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('camera', 'Camera'), ('thermostat', 'Thermostat'), ('sensor', 'Sensor')], help_text='Logical type of device, used for UI and behavior.', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='external_id',
            field=models.CharField(blank=True, help_text='Provider-specific identifier, e.g. Google Home device ID.', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='integration',
            field=models.CharField(choices=[('local', 'Local'), ('google_home', 'Google Home'), ('nest', 'Nest'), ('ring', 'Ring'), ('other', 'Other')], default='local', help_text='Which integration this device is backed by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_on',
            field=models.BooleanField(default=False, help_text='Logical on/off state of the device.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='position_x',
            field=models.FloatField(default=10.0, help_text='Percentage from left (0–100) for room canvas placement.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='position_y',
            field=models.FloatField(default=10.0, help_text='Percentage from top (0–100) for room canvas placement.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='access_token',
            field=models.CharField(blank=True, help_text='OAuth or API token for the provider.', max_length=255),
        ),
        migrations.AlterField(
            model_name='integration',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary provider-specific configuration or state.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Refresh token if applicable.', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='Optional external URL for a background image. Prefer using the uploaded background_image field.'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['room'], name='automation__room_id_ecd729_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['room', 'device_type'], name='automation__room_id_4cf2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['integration'], name='automation__integra_08cd66_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['owner', 'provider'], name='automation__owner_i_32d444_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['owner', 'is_active'], name='automation__owner_i_a8ee31_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner', 'slug'], name='automation__owner_i_80afff_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner', 'created_at'], name='automation__owner_i_126ed9_idx'),
        ),
    ]
