# Generated by Django 5.0.6 on 2025-11-28 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_device_options_alter_integration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many decimals to show in the UI.'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_kind',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('hybrid', 'Hybrid')], default='sensor', help_text='Whether this behaves as a sensor, actuator, or both.', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='is_percentage',
            field=models.BooleanField(default=False, help_text='If true, treat value as 0–100% and show accordingly.'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, help_text='When last_value was updated.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_value',
            field=models.FloatField(blank=True, help_text='Last engineering value (after scaling).', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_value_raw',
            field=models.CharField(blank=True, help_text='Raw value as received (before scaling / parsing).', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Optional maximum engineering value.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Optional minimum engineering value.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='signal_type',
            field=models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('string', 'String')], default='analog', help_text='Analog/digital/string – used for UI & validation.', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, help_text='Display unit, e.g. °C, %, bar.', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='integration',
            field=models.CharField(choices=[('local', 'Local'), ('google_home', 'Google Home'), ('nest', 'Nest'), ('ring', 'Ring'), ('other', 'Other')], default='local', help_text='Which integration this device is conceptually backed by.', max_length=32),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connector_type', models.CharField(choices=[('mqtt', 'MQTT'), ('plc_modbus', 'PLC (Modbus/TCP)'), ('plc_opcua', 'PLC (OPC UA)'), ('nest_api', 'Nest API'), ('http_api', 'HTTP API'), ('other', 'Other')], max_length=32)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('base_topic', models.CharField(blank=True, help_text='MQTT base topic prefix, if applicable.', max_length=255)),
                ('base_path', models.CharField(blank=True, help_text='HTTP base path or OPC UA base node, if applicable.', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Arbitrary connector-specific configuration.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable a connector without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, help_text='Optional link to a higher-level provider integration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectors', to='automation.integration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'Input (Sensor)'), ('output', 'Output (Actuator)')], help_text='Input (read) or Output (write).', max_length=16)),
                ('address', models.CharField(help_text='MQTT topic, PLC tag/address, OPC UA node, or API path.', max_length=255)),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor applied to raw numeric values.')),
                ('offset', models.FloatField(default=0.0, help_text='Offset applied after scaling.')),
                ('true_value', models.CharField(blank=True, help_text="Raw value representing TRUE (e.g. '1', 'ON').", max_length=64)),
                ('false_value', models.CharField(blank=True, help_text="Raw value representing FALSE (e.g. '0', 'OFF').", max_length=64)),
                ('is_primary', models.BooleanField(default=True, help_text='If multiple endpoints, which one is primary for UI.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra endpoint-specific configuration or flags.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='automation.connector')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='automation.device')),
                ('integration', models.ForeignKey(blank=True, help_text='Optional link to the higher-level provider integration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='automation.integration')),
            ],
            options={
                'ordering': ['device', 'direction', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['owner', 'connector_type'], name='automation__owner_i_1078cc_idx'),
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['owner', 'is_active'], name='automation__owner_i_40c287_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['device'], name='automation__device__d14b41_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['connector'], name='automation__connect_8275c1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceendpoint',
            index=models.Index(fields=['direction'], name='automation__directi_b97892_idx'),
        ),
    ]
